language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - Release
  - Debug

before_install:
  - rustup self update

stages:
  - Build
  - Test
  - Lint
  
stage: Test
script: "cargo test ${Release+--release} --verbose"

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - stage: Build
      script: "cargo build ${Release+--release} --verbose"
    - stage: Lint
      script: cargo fmt -- --check

cache: cargo
