language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - BUILD=--release
  - BUILD=

before_install:
  - rustup self update

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  - stage: Build
    script: "cargo build $BUILD --verbose"
  - stage: Tests
    script: "cargo test $BUILD --verbose"
  - stage: Lint
    script: cargo fmt -- --check

cache: cargo
