language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - BUILD=--release
  - BUILD=

before_install:
  - rustup self update

# stages:
#   - Build
#   - Test
#   - Lint
  
stage: Build
script: "cargo build $BUILD --verbose"
stage: Test
script: "cargo test $BUILD --verbose"

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - stage: Lint
      script: cargo fmt -- --check

cache: cargo
